CREATE TABLE [dbo].[RawData] (
    [DrawNo]   SMALLINT NOT NULL,
    [DrawDate] DATETIME NOT NULL,
    [Plus]          TINYINT  NULL,
    [Number1]       TINYINT  NOT NULL,
    [Number2]       TINYINT  NOT NULL,
    [Number3]       TINYINT  NOT NULL,
    [Number4]       TINYINT  NOT NULL,
    [Number5]       TINYINT  NOT NULL,
    [Number6]       TINYINT  NOT NULL,
    [Number7]       TINYINT  NOT NULL,
    [Number8]       TINYINT  NOT NULL,
    [Number9]       TINYINT  NOT NULL,
    [Number10]      TINYINT  NOT NULL,
    [Number11]      TINYINT  NOT NULL,
    [Number12]      TINYINT  NOT NULL,
    [Number13]      TINYINT  NOT NULL,
    [Number14]      TINYINT  NOT NULL,
    [Number15]      TINYINT  NOT NULL,
    [Number16]      TINYINT  NOT NULL,
    [Number17]      TINYINT  NOT NULL,
    [Number18]      TINYINT  NOT NULL,
    [Number19]      TINYINT  NOT NULL,
    [Number20]      TINYINT  NOT NULL,
    CONSTRAINT [PK_RawData] PRIMARY KEY CLUSTERED ([DrawNo] ASC)
);

